### ISSUE TITLE
Dead link on "Shopping" Page

### ISSUE THREAD

**Issue by luckygreen** [covid-at-home/covid-at-home.github.io#1]
On covid-at-home.info/shopping, the following link results in a 404:

https://www.amazon.de/dp/B085H6Y6HN

**Comment by ropg** [comment]
fixed

**Comment by blijblijblij** [comment]
Still kaput @ropg 

<img width="1258" alt="Screenshot 2020-03-15 21 05 20" src="https://user-images.githubusercontent.com/1648248/76709647-b6a2b980-6700-11ea-84a5-0ff8099fffee.png">

Regards

**Comment by ropg** [comment]
I actually changed it to a working link, and then that broke again. I just took out the link altogether...

**Comment by blijblijblij** [comment]
You are on top this! +1!
