### ISSUE TITLE
virus v disease name clarification

### ISSUE THREAD

**Issue by verawilde** [covid-at-home/covid-at-home.github.io#11]
Tillman writes what Rafael suggested in videochat yesterday suggesting to change intro to reflect virus rather than disease name if it's going to refer to the virus.  

alternately we could just be consistent in referring to the disease by the name the WHO designated. or put a disambiguation somewhere explaining -- virus name (SARS-CoV-2), disease name according to the WHO (COVID-19), also known as (coronavirus even though this is a family of viruses that refers to many including the more deadly SARS "classic" and MERS as well as the less deadly 1/3 of the common cold viruses). 

where is a good middle way between being too pedantic and being crystal clear here? the temptation is often to confuse with detail, while this is intended for an audience that wants it simple and short. discuss.

**Comment by ropg** [comment]
Technically that is more correct, so I changed it.
