### ISSUE TITLE
Loss of sense of smell as marker of COVID-19 infection

### ISSUE THREAD

**Issue by 229c9cf0** [covid-at-home/covid-at-home.github.io#12]
https://www.entuk.org/loss-sense-smell-marker-covid-19-infection
> […]
> There is already good evidence from South Korea, China and Italy that significant numbers of patients with proven COVID-19 infection have developed anosmia/hyposmia. In Germany it is reported that more than 2 in 3 confirmed cases have anosmia. In South Korea, where testing has been more widespread, 30% of patients testing positive have had anosmia as their major presenting symptom in otherwise mild cases. 
> In addition, there have been a rapidly growing number of reports of a significant increase in the number of patients presenting with anosmia in the absence of other symptoms – this has been widely shared on medical discussion boards by surgeons from all regions managing a high incidence of cases. […] I think these patients may be some of the hitherto hidden carriers that have facilitated the rapid spread of COVID-19. Unfortunately, these patients do not meet current criteria for testing or self-isolation.
> […]
> There is potential that if any adult with anosmia but no other symptoms was asked to self-isolate for seven days, in addition to the current symptom criteria used to trigger quarantine, we might be able to reduce the number of otherwise asymptomatic individuals who continue to act as vectors, not realising the need to self-isolate. It will also be an important trigger for healthcare personnel to employ full PPE and help to counter the higher rates of infection found amongst ENT surgeons compared to other healthcare workers.

Maybe include this as a criterion for proactive self-isolation?

**Comment by ropg** [comment]
Yes, read about that, good that you bring it up again... Goes on list for first revision...

**Comment by verawilde** [comment]
Yes, but it's already there - level 2, 1st full paragraph, last sentence:  Later in the infection, symptoms may include loss of smell and taste lasting for several days.
