### ISSUE TITLE
Advice on preventing an infection of the lungs

### ISSUE THREAD

**Issue by verkre** [covid-at-home/covid-at-home.github.io#17]
This advice by a nurse on how to prevent an infection of the lung might be useful for the "when you are sick" section (text is in German); seems like reasonable advice that at the very least will do no harm, even though no studies are quoted in the post.
https://mypflegephilosophie.com/2020/03/20/covid-19-patienten-und-lungenentzundung-ist-vermeidung-und-pravention-eine-moglichkeit-die-kurve-der-verlaufe-zu-flatten/

**Comment by verawilde** [comment]
Thanks! This is excellent. We'll be incorporating some of it into a revision in the works, fleshing out where bits of the advice are already there under "Get Healthy Again" (level 2)...

**Comment by verawilde** [comment]
Updated in new version.
