### ISSUE TITLE
"File an issue" - first bring people to the Github page

### ISSUE THREAD

**Issue by Echolon** [covid-at-home/covid-at-home.github.io#31]
Hello,

I just want to remind to link to the Github repository not directly to a new issue.

It is more helpful to look for other issues first and not being forced to login directly.

Everyone who want to open an issue can still do so.

Cheers & thank you for your website!

**Comment by ropg** [comment]
Glad you like the site...

I think where to link in this case depends on whether we're talking to GitHub-experienced users or the general public. Someone who is not a techie, just reading the page and spotting an error, when confronted with the bells-and-whistles of the entire GitHub kitchen sink, will just be confused and move on. I'd rather deal with a duplicate issue than drop all the people that would simply have no clue how to file one. And those with any experience on GitHub will find their way anyway: the entire kitchen sink is still there after all.

**Comment by Echolon** [comment]
Okay, is fine!
