### ISSUE TITLE
Disposable gloves not recommended in everyday use

### ISSUE THREAD

**Issue by miallo** [covid-at-home/covid-at-home.github.io#32]
Thanks for this great website!

My mother and my stepfather are both working in the medical field and they both appose wearing disposable gloves while shopping. She is searching the article in the medical journal and I will post this as soon as she finds it again. So far I can only point to articles like this: [FAZ](https://www.faz.net/aktuell/gesellschaft/gesundheit/coronavirus/corona-ansteckung-gummihandschuhe-sind-eher-gefahr-als-schutz-16717608.html), [CNBC](https://www.cnbc.com/2020/04/14/can-wearing-medical-gloves-protect-you-from-coronavirus-experts.html), [MorgenPost](https://www.morgenpost.de/vermischtes/article228866365/Arzt-warnt-vor-Einmalhandschuhen-als-Kloake-an-den-Haenden.html)

The main points are:

- Gloves are not impenetrable
- They might give a wrong feeling of safety
- You can spread the virus onto your groceries and when you are at home you don't wear them anymore
- The humidity of the sweat can lead to a faster growth of the bacteria on the skin
- The skin is attacked
- The powdered gloves are highly allergic

**Comment by ropg** [comment]
Hello there. Glad you like the site. Thank you, we'll certainly look into the gloves. Were you reading the german or the english version? Also we'd be curious to hear what they think about briefly wearing gloves when handling known contaminated goods, such as trash or laundry from people sick with COVID-19.

**Comment by miallo** [comment]
Briefly wearing gloves is a good idea, but one has to pay attention on how one pulls them off the hands so that one does not contaminate the hands just later...
