### ISSUE TITLE
what to eat / cook when you SHOULD stay at home?

### ISSUE THREAD

**Issue by 229c9cf0** [covid-at-home/covid-at-home.github.io#4]
(This may be out of scope, but maybe not.)

Currently, there's zero information on food on the shopping list or elsewhere. Given that [some government agencies essentially advise at-risk people to best just _stay at home until this blows over_](https://www.cdc.gov/coronavirus/2019-ncov/specific-groups/high-risk-complications.html), this means stocking up on non-perishable supplies and then cooking with those. This is unfamiliar for many (who are used to incorporating fresh produce), which means there's a risk of an imbalanced diet. Long-term malnutrition over several weeks–months can result in serious problems.

As such, it would be helpful to have a bunch of templates for cooking with cans / jars / dry produce, only allowing some very shelf-stable fresh produce (like onions) or none at all.

I myself lack the necessary knowledge on the nutrition side, but if you have contacts to someone who knows about that stuff I'd be very happy to help. (I've been cooking at CCCB for several years and, with some guidance, should be able to whip up a bunch of templates for food – dals, curries, flatbreads, stews, …)

-----

As a "worst case environment", we could assume a student's dormitory. (Even if you're young, you might still have preexisting conditions and want to _strongly_ avoid going out.) That would result in

 *  no freezer
 *  no oven
 *  single room + bath, no separate cool room to store stuff
     +  (What if you're in a shared apartment… Flee to your parents?)
 *  moths & other bugs eating & infesting your food unless you protect it
 *  what about bringing out the trash? (or cleaning & storing it in-place? Means avoiding waste-generating stuff – stacking rinsed / dried cans is ok, stacking bones probably is not.)

(Non-cooking addition: Basic indoor training regime if you must stay in your room?)

-----

Stuff that would be nice to have:

 *  basic nutritional requirements
     +  "burn rate"
     +  vitamins etc., plus what can realistically be supplemented and what can't
 *  useful spices (they're dry & store well, plus they allow seriously changing the character of meals)
 *  basic "recipe templates" based on cans / dried stuff
 *  how to store stuff (in the worst case environment, or if you have more options)
 *  nice goodies to put in the freezer (if you have one)
 *  what to cook when you have to care for yourself and it's about to get worse (soupy, reheatable stuff?)
 *  what to cook when you're bored and need to kill time (stuff that keeps for weeks)

-----

If this is in scope, ping me and I'll start sketching / drafting stuff. (If this is out of scope, I have plenty of other stuff to do as well… In which case I'll just hope that someone somewhere will write something like this…)

**Comment by ropg** [comment]
Hey.. We're all for it, it should be a separate sub-page, just like the diary, shopping, and probably a few more. There must be prepper-oriented resources that already have some stuff on this. Note that it would be good to tap the slightly saner end of that spectrum. Let's assume a working kitchen of some sort. Also let's assume that many will still shop but less, and that even people that want to avoid that can get regular(-ish) delivery of stuff, so it doesn't all have to keep for extreme lengths of time.

I think our "niche" with this site is to be complete enough that it actually teaches many people something useful without going too overboard. Can always point to external resources. Come to the [video conference](https://meet.jit.si/OngoingTeamMeetingForCovidAtHome) if you feel like chatting about the scope of this.

**Comment by 229c9cf0** [comment]
> Come to the video conference if you feel like chatting about the scope of this.

Currently running around, but probability of me dropping by should approach 1 by Wednesday…

My reasoning for the "worst case environment" is as follows: Anything that requires more stuff is 100% useless in that setting, which leaves those in the worst situations without help… I do intend to focus on stuff that requires more tools / assumes you go outside, but about 20-30% of the stuff should work and keep you alive if you're stuck in a dorm. (And thoughts about trash handling etc. won't need more than one sentence, which is exactly how much you'd need to have other people go "oh, right…" and think about strategies like disposable gloves or whatever.)

I'll probably report back on Tuesday evening, with a basic outline / rough notes.

**Comment by 229c9cf0** [comment]
So the prepper-oriented resources I found fall in one of two classes – a good summary is <https://nwedible.com/preparedness-101-how-to-build-two-week-emergency-pantry/>. TL;DR: either "buy more of what you usually buy" (with no clear specs) or "get ready-made (canned or freeze-dried) food".

However, stuff is starting to pop up – e.g. https://www.youtube.com/watch?v=egvnmbPkRwY – so it's probably enough to mostly collect a bunch of links to what other people suggest? I'll try to keep track of this on the side (and – depending on when I'm awake – will try to reach the video conference when you're still around, 2nd unsuccessful attempt today.)

**Comment by verawilde** [comment]
This seems indeed like a good message board, blog, DIY search topic to me -- important, but beyond the scope of this site at this time. There are lots of great columns and resources out there and people can find ones they like. 

I say that as a cooking nerd, after writing and rewriting a blog draft over several days... and deciding it might be better for people to find out what they like themselves, instead of offering the wisdom that works for me. I found myself segueing into a recipe brainstorming session after a long intro bit on cooking with ingredients that last a long time -- and only liking 2/8 of my recipe drafts. ;) So I think I won't even post about it on my personal blog at the moment. (The main site updates are just more important / urgent at the moment given world events.) 

Thus although I love the topic and it's important, I suggest it's possibly time to close this issue as resolved by reason "scope of site." Agreed?

**Comment by verawilde** [comment]
Scope.
