### ISSUE TITLE
Printable dairy is not easy to print

### ISSUE THREAD

**Issue by juurd** [covid-at-home/covid-at-home.github.io#5]
What a great project! Very clear and useful. But the lay-out of the printable diary is such, that for people like myself who ware not very practical with these kinds of things, it is difficult to get the PDF on one page without making it so small (70%) that it is hardly readable anymore. At 80% it is better, but the information block on the right (name of patient, etc) gets cut in half.

As there is a lot of white, unused space underneath that block, wouldn't is be possible to make the block narrower, meaning, with more lines, but of lesser length. "Patient Name" and 'Sars-CoV-2-positive' would then not be next to each other, but one under the other. Same for Date of birth, and Male/Female, etc. 

That way it would be possible to print at 80% , or maybe even 90 %, without the block being cut in half.
best regards,
juurd eijsvoogel

**Comment by ropg** [comment]
That is good information. Glad to hear this, as we currently have a non-functional printer over here. I will mess with Apple Numbers to see if I can get the bloody margins smaller, I was having some trouble with this earlier.

**Comment by ropg** [comment]
Hi juurd. Could you try now?

**Comment by juurd** [comment]
Great! This way I print it easily at 90 %. Much better. Thanks!

**Comment by ropg** [comment]
I don't understand the 90% part. It's a PDF, it should just print as is, no?

**Comment by juurd** [comment]
Yes, you are right, no need to adjust the size of the page, just print and it fits.
Something else: I didn't quite get what the numbers stand for in this sentence, under Illness diary: 
(Some people use 4-7-8 and others prefer 5-2-5 to try slowing down their inhale-hold-exhale patterns.)

**Comment by eabase** [comment]
It's obviously an Excel sheet, can you just include the Excel instead? 
Also, because the right hand side white part is completely wasted space.

**Comment by ropg** [comment]
That white part is for the notes of that day, so not all that wasted. And it's not Excel but Numbers (Apple's version of Excel). The Numbers version is not linked on the website but checked into the repository in the /images directory.

**Comment by verawilde** [comment]
Is it time to close this issue / is this resolved or do we want to work on printability of the diary some more? Thanks. :)

**Comment by verawilde** [comment]
issue seems mostly resolved
