### ISSUE TITLE
Sheets: double-bag them

### ISSUE THREAD

**Issue by mverwijs** [covid-at-home/covid-at-home.github.io#6]
Put two waterproof sheets on the bed.

If the 'accident' happens in the middle of the night removing the top layer will hopefully be enough. This means more sleep. Sleep is healthy.

**Comment by ropg** [comment]
Good idea, goes on the list for the next text-revision. Have to batch and prioritise cheanges now because of all the translations.

**Comment by verawilde** [comment]
Resolved by incorporating suggestion into shopping page where this is mentioned most explicitly already, in new version.
