### ISSUE TITLE
Resource page

### ISSUE THREAD

**Issue by verawilde** [covid-at-home/covid-at-home.github.io#9]
We discussed adding a resource page and decided to wait until we found a really cool one, and maybe point people to that, instead. Well, here's a really cool one! https://github.com/cwoomi/cert-covid19

Shall we link to it? Where, in what context? Discuss...

**Comment by ropg** [comment]
It's quite German-focussed, with many links also in German. Still worth being included, possibly everywhere, but we might want to look for a few more resources like this. Or get them to create an English-language subset even.

**Comment by verawilde** [comment]
I like the idea of compiling a helpful lists of other lists (of course I do :) ... But I thought we said in another discussion that we were not gonna do a resource list because other sites have already done that.

**Comment by verawilde** [comment]
making a new resources page of external links (starting with this and the other open issue / the WHO research one), in the new version.
